DEVICE_PATH := device/motorola/cancunf

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_BOOTLOADER_BOARD_NAME := cancunf
TARGET_BOARD_PLATFORM := mt6855

TARGET_NO_KERNEL := true
TARGET_USES_RECOVERY_AS_BOOT := true

BOARD_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_DTBOIMG_PARTITION_SIZE := 25165824

TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888

TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_INCLUDE_FASTBOOTD := true
TW_USE_TOOLBOX := true
TW_HAS_MTP := true
