TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a

TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := cancunf

BOARD_HAS_NO_REAL_SDCARD := true
BOARD_USES_RECOVERY_AS_BOOT := true

TW_THEME := portrait_hdpi
TW_INCLUDE_NTFS := true
TW_INCLUDE_CRYPTO := true
